### ISSUE TITLE
Use a background thread

### ISSUE THREAD

**Issue by AshleyDeng** [passslot/cordova-plugin-passbook#4]
Hi,

I run this plugin with a real device and it gave me:
`2016-10-03 17:15:48.486 [287:48508] THREAD WARNING: ['Passbook'] took '40.332031' ms. Plugin should use a background thread.
2016-10-03 17:15:48.512 [287:48508] ERROR: "No data supplied"`

Which essentially preventing the plugin to be used correctly. Apple doesn't like blocking the UI which means anything running more than 10ms will be aborted. Weird thing is, I have tested it on emulators and it worked fine. 

Any suggestions or fix?

**Comment by AshleyDeng** [comment]
Just fixed the issue by using the latest version.
`cordova plugin add https://github.com/passslot/cordova-plugin-passbook`

Close issue.

**Comment by passslot** [comment]
Time consuming operations (such as downloading) are done in the background. We only do things on the UI thread that are necessary. 

If the issues re-appears, please re-open the issue provide some more details on how you call the plugin.
