### ISSUE TITLE
Plugin ID not in sync as the npmjs name

### ISSUE THREAD

**Issue by hx-markterry** [passslot/cordova-plugin-passbook#6]
The plugin is titled `cordova-plugin-passbook` on npmjs.org but the plugin ID is still set to the older cordova plugin registry name of: `com.passslot.cordova.plugin.passbook`. This means that when you save the plugin to your `config.xml` using:

    cordova plugin add cordova-plugin-passbook --save

It stores the wrong name so future downloads are very slow as cordova presumes the plugin does not exist on npmjs.org.

**Comment by passslot** [comment]
thanks for reporting this, we have now corrected the plugin ID
