### ISSUE TITLE
Add to Wallet breaks some of the app's interactions

### ISSUE THREAD

**Issue by embedded-spirit** [passslot/cordova-plugin-passbook#7]
With latest versions of Cordova (6.x.x) the **shouldOverrideLoadWithRequest** method after being called by Cordova seems to block some of the app's functionality, e.g. getting email composer by clicking on `<a href="mailto:?subject...".>`

**Comment by passslot** [comment]
thanks for the report. Are you able to provide a sample project so that we can reproduce your problem?
